baseURL = "http://w5ac.tamu.edu/"
languageCode = "en-us"
title = "W5AC, The Texas A&M Amateur Radio Club"


[menu]
  [[menu.navmain]]
    identifier = "about"
    name = "About Us"
  [[menu.navmain]]
    identifier = "activities"
    name = "Activities"
  [[menu.navmain]]
    identifier = "resources"
    name = "Club Resources"
  [[menu.navmain]]
    identifier = "join"
    name = "Join!"
